import EventImage from "../assets/events_photo.jpg";

export const events = [
    {
        id: 1,
        eventName: "Jalinan Raya",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DWPgAxmky6q/?img_index=1",
        eventDescription: "very cool and very descriptive description",
        eventIsDone: false,
        eventDate: new Date("2026-05-20"),
        eventTag: "Social",
        page: 1,
    },
    {
        id: 2,
        eventName: "Bersatu Trials",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DV7o4eZmPHH/?img_index=1",
        eventDescription: "even cooler and even more descriptive description",
        eventIsDone: false,
        eventDate: new Date("2026-05-28"),
        eventTag: "Social",
        page: 1,
    },
    {
        id: 3,
        eventName: "Clash of UMSA",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: false,
        eventDate: new Date("2026-06-21"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 4,
        eventName: "Clash of UMSA",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: false,
        eventDate: new Date("2026-03-21"),
        eventTag: "Social",
        page: 1,
    },
    {
        id: 5,
        eventName: "Clash of UMSA 2026",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2026-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 6,
        eventName: "Clash of UMSA 2025",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2025-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 7,
        eventName: "Clash of UMSA 2024",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2024-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 8,
        eventName: "Clash of UMSA 2023",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2023-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 9,
        eventName: "Clash of UMSA 2022",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2022-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 10,
        eventName: "Clash of UMSA 21",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2021-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 11,
        eventName: "Clash of UMSA 20",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2020-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 12,
        eventName: "Clash of UMSA 19",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2019-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 13,
        eventName: "Clash of UMSA 18",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2018-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 14,
        eventName: "Clash of UMSA 17",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2017-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 15,
        eventName: "Clash of UMSA 16",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2016-04-20"),
        eventTag: "Competition",
        page: 1,
    },
    {
        id: 16,
        eventName: "Clash of UMSA 15",
        eventImage: EventImage,
        eventLink: "https://www.instagram.com/p/DVrOmhNk_kI/",
        eventDescription: "even even cooler and way wayyyyy more descriptive description",
        eventIsDone: true,
        eventDate: new Date("2015-04-20"),
        eventTag: "Competition",
        page: 1,
    },
];
